# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

category_0 = Category.create!(name: 'Category0')
category_1 = Category.create!(name: 'Category1')
category_2 = Category.create!(name: 'Category2')
category_3 = Category.create!(name: 'Category3')
category_00 = Category.create!(name: 'Category00', parent: category_0)
category_10 = Category.create!(name: 'Category10', parent: category_1)
category_11 = Category.create!(name: 'Category11', parent: category_1)
category_20 = Category.create!(name: 'Category20', parent: category_2)
category_21 = Category.create!(name: 'Category21', parent: category_2)
category_22 = Category.create!(name: 'Category22', parent: category_2)
category_30 = Category.create!(name: 'Category30', parent: category_3)
category_31 = Category.create!(name: 'Category31', parent: category_3)
category_32 = Category.create!(name: 'Category32', parent: category_3)
category_33 = Category.create!(name: 'Category33', parent: category_3)
category_000 = Category.create!(name: 'Category000', parent: category_00)
category_001 = Category.create!(name: 'Category001', parent: category_00)
category_210 = Category.create!(name: 'Category210', parent: category_21)
category_211 = Category.create!(name: 'Category211', parent: category_21)
category_330 = Category.create!(name: 'Category330', parent: category_33)
category_331 = Category.create!(name: 'Category331', parent: category_33)
category_332 = Category.create!(name: 'Category332', parent: category_33)

product0000 = Product.create!(pr_name: 'Product0000', child: category_000)
product0010 = Product.create!(pr_name: 'Product0010', child: category_001)
product100 = Product.create!(pr_name: 'Product100', child: category_10)
product110 = Product.create!(pr_name: 'Product110', child: category_11)
product200 = Product.create!(pr_name: 'Product200', child: category_20)
product2100 = Product.create!(pr_name: 'Product2100', child: category_210)
product2110 = Product.create!(pr_name: 'Product2110', child: category_211)
product220 = Product.create!(pr_name: 'Product220', child: category_22)
product300 = Product.create!(pr_name: 'Product300', child: category_30)
product310 = Product.create!(pr_name: 'Product310', child: category_31)
product320 = Product.create!(pr_name: 'Product320', child: category_32)
product3300 = Product.create!(pr_name: 'Product3300', child: category_330)
product3310 = Product.create!(pr_name: 'Product3310', child: category_331)
product3320 = Product.create!(pr_name: 'Product3320', child: category_332)
product3321 = Product.create!(pr_name: 'Product3321', child: category_332)